### ISSUE TITLE
Cousebase not installed

### ISSUE THREAD

**Issue by yafeearun** [couchbaselabs/todolite-ionic2#2]
there is a error cousebase lite not installed every time when i take a new build what i was missed?

**Comment by Murilo-Perrone** [comment]
In case you are using "ionic serve" command, try running it on a USB connected phone device, with developer mode enabled. Then run "ionic cordova emulate android -cs", "ionic codova run ios -cs" etc.  The -l (or --liveload) option will allow faster development, if it works for you. Ionic serve won't work because couchbase lite plugin only runs on native environment, not on the browser. Thus when running in a browser, the window.CBlite object is undefined. Hope that helps.

**Comment by raghuaje** [comment]
I am getting same issue on web browser , 
so i run on android devices then in debug console following error come

DEBUG CONSOLE
Attaching to android
Forwarding debug port
Attaching to app.
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
deviceready has not fired after 5 seconds.
Native: deviceready did not fire within 2000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.
DEVICE READY FIRED AFTER 5558 ms
EXCEPTION: Unexpected end of JSON input
ORIGINAL STACKTRACE:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.xhr.onreadystatechange (file:///android_asset/www/build/vendor.js:70529:37)
    at XMLHttpRequest.n [as _onreadystatechange] (file:///android_asset/www/build/polyfills.js:1:1189)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14051)
